services:
  web:
    build: 
      context: .
    ports:
      - "8080:8080"
      # - "8081:8081"
    container_name: pong
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    name: transcendence
