events {}

http {
    include mime.types;
    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=3r/s;

    server {
        listen 8000 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/selfsigned.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/user/login {
            limit_req zone=auth_limit burst=2 nodelay;
            if ($http_x_internal != "true") {
                return 403;
            }
            proxy_pass http://user:3001/login;
        }

        location /api/user/register {
            limit_req zone=auth_limit burst=2 nodelay;
            if ($http_x_internal != "true") {
                return 403;
            }
            proxy_pass http://user:3001/register;
        }

        location /api/user/google {
            limit_req zone=auth_limit burst=2 nodelay;
            if ($http_x_internal != "true") {
                return 403;
            }
            proxy_pass http://user:3001/google;
        }

        location /api/user/update {
            limit_req zone=auth_limit burst=2 nodelay;
            if ($http_x_internal != "true") {
                return 403;
            }
            proxy_pass http://user:3001/update;
        }

        location /api/user/update-google {
            limit_req zone=auth_limit burst=2 nodelay;
            if ($http_x_internal != "true") {
                return 403;
            }
            proxy_pass http://user:3001/update-google;
        }

        location /api/user/ {
            if ($http_x_internal != "true") {
                return 403;
            }
            proxy_pass http://user:3001/;
        }

        location /api/game/ {
            proxy_pass http://game:3002/;
        }

        location /api/tournament/ {
            proxy_pass http://tournament:3003/;
        }

        location /api/page_content/ {
            proxy_pass http://page_content:3004/;
        }

        location /api/notification/ {
            proxy_pass http://notification:3005/;
        }

        location /api/guest/ {
            proxy_pass http://guest:3006/;
        }
    }
}
