# Use an official Node.js image as the base image
FROM node:22
RUN npm install -g npm@latest

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY userService/package*.json ./
# COPY pong.html ./

# Install dependencies inside the container
RUN npm install

COPY userService/ ./

# Compile TypeScript to JavaScript
RUN npm run build

RUN mkdir -p /app/uploads
RUN mkdir -p /app/uploads/profile_pictures
COPY userService/uploads/profilePicture.png /app/uploads/profile_pictures

# Expose port 3001
EXPOSE 3001

CMD [ "npm", "run", "start" ]
