# Use an official Node.js image as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./
# COPY pong.html ./

# Install dependencies inside the container
RUN npm install

COPY . .

# Compile TypeScript to JavaScript
RUN npm run build

RUN mkdir -p /app/uploads
RUN mkdir -p /app/uploads/profile_pictures

# Expose port 3001
EXPOSE 3001

CMD [ "npm", "run", "start" ]