# Use an official Node.js image as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY pageContent/package*.json ./
# COPY pong.html ./

# Install dependencies inside the container
RUN npm install

COPY pageContent/ ./
RUN mkdir -p /app/shared/types

COPY shared/types /app/shared/types

# Compile TypeScript to JavaScript
RUN npm run build

# Expose port 3004
EXPOSE 3004

CMD [ "npm", "run", "start" ]