services:
  nginx:
    build:
      context: ./
      dockerfile: backend/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8000:8000"
    depends_on:
      - user
      - game
      # - tournament
      - page_content
    networks:
      - transcendanse
    env_file:
      - .env
    restart: unless-stopped

  user:
    build:
      context: ./backend
      dockerfile: userService/Dockerfile
    container_name: user
    expose:
      - "3001"
    volumes:
      - user-db:/app/db
      - user-profilePicture:/app/uploads/profile_pictures
    env_file:
      - .env
    networks:
      - transcendanse
    restart: unless-stopped

  game:
    build:
      context: ./backend/gameService
    container_name: game
    expose:
      - "3002"
    volumes:
      - game-db:/app/db
    env_file:
      - .env
    networks:
      - transcendanse
    restart: unless-stopped

  tournament:
    build:
      context: ./backend/tournamentService
    container_name: tournament
    expose:
      - "3003"
    volumes:
      - tournament-db:/app/tournament.sqlite
    env_file:
      - .env
    networks:
      - transcendanse
    restart: unless-stopped
  notification:
    build:
      context: ./backend/notificationService
      # dockerfile: Dockerfile
    container_name: notification
    expose:
      - "3005"
    volumes:
      - notification-db:/app/db
    env_file:
      - .env
    networks:
      - transcendanse
    restart: unless-stopped

  page_content:
    build:
      context: ./backend
      dockerfile: pageContent/dockerfile
    container_name: page_content
    expose:
      - '3004'
    volumes:
      - page_content-db:/app/db
    env_file:
      - .env
    networks:
      - transcendanse
    restart: unless-stopped

volumes:
  user-db:
    name: user
    driver: local
    driver_opts:
      device: ~/data/user
      o: bind
      type: none
  user-profilePicture:
    name: profile_pictures
    driver: local
    driver_opts:
      device: ~/data/user/uploads/profile_pictures
      o: bind
      type: none
  page_content-db:
    name: page_content
    driver: local
    driver_opts:
      device: ~/data/page_content
      o: bind
      type: none
  game-db:
  notification-db:
  tournament-db:
    name: tournament
    driver: local
    driver_opts:
      device: ~/data/tournament
      o: bind
      type: none

networks:
  transcendanse:
    driver: bridge
