# Use an official Node.js image as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./
# COPY pong.html ./

# Install dependencies inside the container
RUN npm install
# # Install cookie and session middleware
# RUN npm install cookie-parser express-session --save
RUN npm i @fastify/session 
RUN npm install @fastify/cors
# npm install concurrently --save
# "scripts": {
#   "start": "concurrently \"node dist/game.js\" \"node dist/other.js\""
# }

# COPY src/frontend/sharedValuesPong.ts ./sharedValuesPong.ts
COPY . .

# Compile TypeScript to JavaScript

RUN npm run build

# Expose port 3002
EXPOSE 3002

CMD [ "npm", "run", "start" ]
# CMD [ "node", "game.js" ]